name: flutter_blur_effects
description: "This Flutter package provides a variety of flutter image blur effects"
version: 0.0.1
homepage: "https://github.com/bijith-git/flutter_blur_effect"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/name_drop.frag
    - shaders/box.frag
    - shaders/gaussian.frag
    - shaders/lens.frag
    - shaders/mean.frag
    - shaders/motion.frag
    - shaders/radial.frag
    - shaders/shape.frag
    - shaders/smart.frag
    - shaders/surface.frag
    - shaders/tilt_shift.frag
    - shaders/glass.frag
    - shaders/tilt_shift_gaussian.frag
